apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "generic-three-tier.frontend.fullname" . }}
  labels:
    app: {{ template "generic-three-tier.name" . }}
    chart: {{ template "generic-three-tier.chart" . }}
    release: {{ .Release.Name }}
    component: frontend
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "generic-three-tier.name" . }}
      release: {{ .Release.Name }}
      component: frontend
  template:
    metadata:
      labels:
        app: {{ template "generic-three-tier.name" . }}
        release: {{ .Release.Name }}
        component: frontend
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
{{- if gt (len .Values.frontend.config.data) 0 }}
{{- if gt (len .Values.frontend.config.advancedMounts) 0 }}
{{- range .Values.frontend.config.advancedMounts }}
            - name: config
{{ toYaml . | indent 14 }}
{{- end }}
{{- else }}
            - name: config
              mountPath: {{ .Values.frontend.config.simpleMountPath }}
{{- end }}
{{- end }}
{{- if gt (len .Values.frontend.secrets.data) 0 }}
{{- if gt (len .Values.frontend.secrets.advancedMounts) 0 }}
{{- range .Values.frontend.secrets.advancedMounts }}
            - name: secrets
{{ toYaml . | indent 14 }}
{{- end }}
{{- else }}
            - name: secrets
              mountPath: {{ .Values.frontend.secrets.simpleMountPath }}
{{- end }}
{{- end }}
          resources:
{{ toYaml .Values.frontend.resources | indent 12 }}
    {{- with .Values.frontend.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.frontend.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.frontend.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
{{- if gt (len .Values.frontend.config.data) 0 }}
        - name: config
          configMap:
            name: {{ include "generic-three-tier.frontend.fullname" . -}}
{{- end }}
{{- if gt (len .Values.frontend.secrets.data) 0 }}
        - name: secrets
          secret:
            secretName: {{ include "generic-three-tier.frontend.fullname" . -}}
{{- end }}
